<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
    const STATUS_RESERVED = 'reserved';
    const STATUS_ACTIVE = 'active';
    const STATUS_CANCELLED = 'cancelled';

    protected $fillable = [
        'name',
        'contract_code',
        'license_code',
        'status',
        'brand_id',
        'position_list',
        'days_diff',
        'position_price',
        'from_ts',
        'to_ts',
        'discount_type',
        'discount_value',
        'discount_max',
        'total_discount',
        'total_price',
        'created_by',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


    }

    protected $appends = ['status_text', 'status_html'];

    public function brand()
    {
        return $this->belongsTo('App\Models\Brand');
    }

    public function getDefaultStatus(): string
    {
        return static::STATUS_RESERVED;
    }

    /**
     * Get the user's status.
     *
     * @return string
     */
    public function getStatusTextAttribute()
    {
        return $this->status ? ucfirst($this->status) : ucfirst('none');
    }

    public function getStatusHtmlAttribute()
    {
        $sttHtml = 'None';
        if ($this->status) {
            $sttClassCss = 'default';
            switch ($this->status) {
                case static::STATUS_CANCELLED:
                    $sttClassCss = 'danger';
                    break;
                case static::STATUS_ACTIVE:
                    $sttClassCss = 'success';
                    break;
                case static::STATUS_RESERVED:
                    $sttClassCss = 'warning';
                    break;
            }

            $sttHtml = '<span class="badge badge-'.$sttClassCss.'">'.$this->status_text.'</span>';
        }

        return $sttHtml;
    }
}
